"""Add Telegram User ID Bigint To Calls

Revision ID: 650aff9a0d41
Revises: a760c3640f52
Create Date: 2026-03-19 04:41:26.510703

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "650aff9a0d41"
down_revision: Union[str, Sequence[str], None] = "a760c3640f52"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "calls", sa.Column("telegram_user_id", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("ix_calls_telegram_user_id"), "calls", ["telegram_user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_calls_telegram_user_id"), table_name="calls")
    op.drop_column("calls", "telegram_user_id")
    # ### end Alembic commands ###
