"""add api usage logs

Revision ID: 841389b1848c
Revises: 7c351d626ca2
Create Date: 2026-02-27 02:30:31.370384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '841389b1848c'
down_revision: Union[str, Sequence[str], None] = '7c351d626ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('duration_secs', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('influencer_id', sa.String(), nullable=True),
    sa.Column('chat_id', sa.String(), nullable=True),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_api_usage_cat_created', 'api_usage_logs', ['category', 'created_at'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_category'), 'api_usage_logs', ['category'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_influencer_id'), 'api_usage_logs', ['influencer_id'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_model'), 'api_usage_logs', ['model'], unique=False)
    op.create_index(op.f('ix_api_usage_logs_user_id'), 'api_usage_logs', ['user_id'], unique=False)
    op.create_index('ix_api_usage_model_created', 'api_usage_logs', ['model', 'created_at'], unique=False)
    op.create_index('ix_api_usage_provider_created', 'api_usage_logs', ['provider', 'created_at'], unique=False)
    op.create_index('ix_api_usage_user_created', 'api_usage_logs', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_api_usage_user_created', table_name='api_usage_logs')
    op.drop_index('ix_api_usage_provider_created', table_name='api_usage_logs')
    op.drop_index('ix_api_usage_model_created', table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_user_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_model'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_influencer_id'), table_name='api_usage_logs')
    op.drop_index(op.f('ix_api_usage_logs_category'), table_name='api_usage_logs')
    op.drop_index('ix_api_usage_cat_created', table_name='api_usage_logs')
    op.drop_table('api_usage_logs')
    # ### end Alembic commands ###
