export const Paths = {
    all: "*",
    root: "/",
    influencerProfile: (username = ":username") => `/${username}`,
    disclaimer: "/disclaimer",
    updateProfile: "/update-profile",
    join: "/join",
    welcome: "/welcome",
    incomeDialog: "/income-dialog",
    profileSurvey: "/profile-survey",
    thankYou: "/thank-you",
    profileSurveyForm: "/profile-survey-form",
    voiceTerms: "/voice-terms",
    influencerHome: "/influencer-home",
    influencerHomeExpired: "/influencer-home-expired",
    intencionInfluencerHome: "/intencion-influencer-home",

    login: "/login",
    register: (username = ":username") => `/${username}/register`,
    registerVerify: "/register/verify",
    resetPassword: "/reset-password",
    forgotPassword: "/forgot-password",
    verifyEmail: "/verify-email",
    admin: {
        influencer: "/admin/influencer",
        prompts: "/admin/prompts",
        relationship: "/admin/relationship",
        preInfluencers: "/admin/pre-influencers",
        preInfluencerDetail: (id = ":pre_influencer_id") =>
            `/admin/pre-influencers/${id}`,
        knowledge: "/admin/knowledge",
        chatHistory: "/admin/chat-history",
        analytics: "/admin/analytics",
    },
    mjDashboard: "/mj/dashboard",

    voice: "/voice",
    home: "/home",
    profile: "/profile",
    chat: (userId = ":user_id") => `/chat/${userId}`,
    call: (conversationId = ":conversation_id") => `/call/${conversationId}`,
    paypalReturn: "/paypal/return",
    paypalCancel: "/paypal/cancel",
    diditReturn: "/didit/return",
    profileSelector: "/profile-selector",
    adultMode: "/adult-mode",
    underage: "/underage",

    influencerAudioManager: (influencerId = ":influencer_id") =>
        `/influencer/${influencerId}/audio-manager`,

    testButtons: "/test/buttons",
    testProfilePage: "/test/profile-page",
    chatInfluencerBarPreview: "/test/chat-influencer-bar-preview",
} as const;
