export const Paths = {
    all: "*",
    influencerProfile: (username = ":username") => `/${username}`,
    testButtons: "/test-buttons",
    updateProfile: "/update-profile",
    join: "/join",
    welcome: "/welcome",
    incomeDialog: "/income-dialog",
    profileSurvey: "/profile-survey",
    thankYou: "/thank-you",
    profileSurveyForm: "/profile-survey-form",
    voiceTerms: "/voice-terms",
    influencerHome: "/influencer-home",
    influencerHomeExpired: "/influencer-home-expired",
    intencionInfluencerHome: "/intencion-influencer-home",

    login: "/login",
    register: (username = ":username") => `/${username}/register`,
    registerVerify: "/register/verify",
    resetPassword: "/reset-password",
    forgotPassword: "/forgot-password",
    verifyEmail: "/verify-email",
    admin: {
        influencer: "/admin/influencer",
        prompts: "/admin/prompts",
        relationship: "/admin/relationship",
        preInfluencers: "/admin/pre-influencers",
    },
    mjDashboard: "/mj/dashboard",

    voice: "/voice",
    home: "/home",
    profile: "/profile",
    chat: (userId = ":user_id") => `/chat/${userId}`,
    call: (conversationId = ":conversation_id") => `/call/${conversationId}`,
    paypalReturn: "/paypal/return",
    paypalCancel: "/paypal/cancel",
    profileSelector: "/profile-selector",

    influencerAudioManager: (influencerId = ":influencer_id") => `/influencer/${influencerId}/audio-manager`,
} as const;
