"""Add knowledge table

Revision ID: 37c713f63774
Revises: 6a2b9d1e4c3f
Create Date: 2026-02-24 10:01:16.490463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
import pgvector.sqlalchemy

# revision identifiers, used by Alembic.
revision: str = '37c713f63774'
down_revision: Union[str, Sequence[str], None] = '6a2b9d1e4c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_knowledge_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('influencer_id', name='uq_influencer_knowledge_documents_influencer_id')
    )
    op.create_index(op.f('ix_influencer_knowledge_documents_influencer_id'), 'influencer_knowledge_documents', ['influencer_id'], unique=False)
    op.create_table('influencer_knowledge_chunks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', Vector(1536), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['influencer_knowledge_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_influencer_knowledge_chunks_document_id'), 'influencer_knowledge_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_influencer_knowledge_chunks_influencer_id'), 'influencer_knowledge_chunks', ['influencer_id'], unique=False)
    op.drop_index(op.f('ix_identity_ver_session'), table_name='identity_verifications')
    op.create_index('ix_identity_ver_session', 'identity_verifications', ['session_id'], unique=False)
    op.create_index(op.f('ix_identity_verifications_session_id'), 'identity_verifications', ['session_id'], unique=True)
    op.create_index(op.f('ix_identity_verifications_user_id'), 'identity_verifications', ['user_id'], unique=False)
    op.drop_index(op.f('memories_embedding_cosine_idx'), table_name='memories', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('messages_embedding_cosine_idx'), table_name='messages', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('messages_embedding_cosine_idx'), 'messages', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('memories_embedding_cosine_idx'), 'memories', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('ix_identity_verifications_user_id'), table_name='identity_verifications')
    op.drop_index(op.f('ix_identity_verifications_session_id'), table_name='identity_verifications')
    op.drop_index('ix_identity_ver_session', table_name='identity_verifications')
    op.create_index(op.f('ix_identity_ver_session'), 'identity_verifications', ['session_id'], unique=True)
    op.drop_index(op.f('ix_influencer_knowledge_chunks_influencer_id'), table_name='influencer_knowledge_chunks')
    op.drop_index(op.f('ix_influencer_knowledge_chunks_document_id'), table_name='influencer_knowledge_chunks')
    op.drop_table('influencer_knowledge_chunks')
    op.drop_index(op.f('ix_influencer_knowledge_documents_influencer_id'), table_name='influencer_knowledge_documents')
    op.drop_table('influencer_knowledge_documents')
    # ### end Alembic commands ###
