"""Add knowledge sync table

Revision ID: 7c351d626ca2
Revises: 37c713f63774
Create Date: 2026-02-24 11:36:47.463610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c351d626ca2'
down_revision: Union[str, Sequence[str], None] = '37c713f63774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_knowledge_sync',
    sa.Column('influencer_id', sa.String(), nullable=False),
    sa.Column('eleven_document_id', sa.String(), nullable=False),
    sa.Column('eleven_document_name', sa.String(), nullable=True),
    sa.Column('eleven_document_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('influencer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('influencer_knowledge_sync')
    # ### end Alembic commands ###
