"""add adult call fields to calls

Revision ID: a760c3640f52
Revises: 3919d878330c
Create Date: 2026-03-18 06:28:10.739861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a760c3640f52'
down_revision: Union[str, Sequence[str], None] = '3919d878330c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calls', sa.Column('is_adult_call', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('calls', sa.Column('adult_character_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('calls', 'adult_character_id')
    op.drop_column('calls', 'is_adult_call')
    # ### end Alembic commands ###
