"""add provider column paypal topup

Revision ID: a7fd0f87cb08
Revises: 8297a97dc75d
Create Date: 2026-03-05 04:26:25.419619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fd0f87cb08'
down_revision: Union[str, Sequence[str], None] = '8297a97dc75d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('paypal_topups', sa.Column('provider', sa.String(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paypal_topups', 'provider')
    # ### end Alembic commands ###
