"""add short discription to adult characters

Revision ID: a8734854683b
Revises: 9b4b3b2f1c0d
Create Date: 2026-03-16 23:22:07.757659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8734854683b'
down_revision: Union[str, Sequence[str], None] = '9b4b3b2f1c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('adult_characters', sa.Column('short_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('adult_characters', 'short_description')
    # ### end Alembic commands ###
