"""drop influencers daily_scripts

Revision ID: cb0ae8ad63ee
Revises: 8c4d9f2a1b7e
Create Date: 2026-04-22 02:08:54.060814

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb0ae8ad63ee"
down_revision: Union[str, Sequence[str], None] = "8c4d9f2a1b7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_column("influencers", "daily_scripts")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "influencers",
        sa.Column(
            "daily_scripts",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
