"""Add influencer character meta table

Revision ID: d7655a7d1e39
Revises: d823d8c805aa
Create Date: 2026-03-12 06:16:09.700044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd7655a7d1e39'
down_revision: Union[str, Sequence[str], None] = 'd823d8c805aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('influencer_character_meta',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('influencer_id', sa.String(), nullable=False),
        sa.Column('character_id', sa.Integer(), nullable=False),
        sa.Column('photo_key', sa.String(), nullable=True),
        sa.Column('video_key', sa.String(), nullable=True),
        sa.Column('meta_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['character_id'], ['adult_characters.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['influencer_id'], ['influencers.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('influencer_id', 'character_id', name='uq_influencer_character_meta_pair')
    )
    op.create_index('ix_influencer_character_meta_character_id', 'influencer_character_meta', ['character_id'], unique=False)
    op.create_index('ix_influencer_character_meta_influencer_id', 'influencer_character_meta', ['influencer_id'], unique=False)
    op.create_index('ix_influencer_character_meta_is_active', 'influencer_character_meta', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_influencer_character_meta_is_active', table_name='influencer_character_meta')
    op.drop_index('ix_influencer_character_meta_influencer_id', table_name='influencer_character_meta')
    op.drop_index('ix_influencer_character_meta_character_id', table_name='influencer_character_meta')
    op.drop_table('influencer_character_meta')
    # ### end Alembic commands ###
