"""Add adult characters table

Revision ID: d823d8c805aa
Revises: a7fd0f87cb08
Create Date: 2026-03-12 05:43:18.489194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd823d8c805aa'
down_revision: Union[str, Sequence[str], None] = 'a7fd0f87cb08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adult_characters',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('slug', sa.String(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('prompt_template', sa.Text(), nullable=False),
        sa.Column('default_artwork_key', sa.String(), nullable=True),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('slug')
    )
    op.create_index('ix_adult_characters_display_order', 'adult_characters', ['display_order'], unique=False)
    op.create_index('ix_adult_characters_is_active', 'adult_characters', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_adult_characters_is_active', table_name='adult_characters')
    op.drop_index('ix_adult_characters_display_order', table_name='adult_characters')
    op.drop_table('adult_characters')
    # ### end Alembic commands ###
