const COMPANY_NAME = "TeaseMe";
const SUPPORT_EMAIL = "support@teaseme.live";
const LEGAL_EMAIL = "legal@teaseme.live";
const lastUpdated = "23 December 2025";
const contentAgreementLastUpdated = "13 May 2026";

export const terms = {

terms: {
  title: "Terms and Conditions",
  lastUpdated,
  intro: [
    `These Terms and Conditions (“Terms”) govern your access to and use of the services, applications, and website operated by ${COMPANY_NAME} (“we”, “us”, or “our”). By accessing or using the platform, you acknowledge that you have read, understood, and agree to be bound by these Terms. If you do not agree to these Terms, you must not access or use the Services.`,
  ],
  sections: [

    {
      heading: "Service Description",
      paragraphs: [
        `${COMPANY_NAME} provides a digital entertainment platform offering AI-generated conversational experiences, including text and audio interactions. All interactions are created and delivered by automated systems and are not provided by live humans. The platform is intended solely for entertainment and simulated engagement purposes.`,
        `You acknowledge that the Services do not constitute professional advice of any kind, including legal, medical, financial, or psychological advice. Any reliance on content generated by the platform is solely at your own risk.`,
      ],
    },

    {
      heading: "Eligibility",
      paragraphs: [
        `You must be at least eighteen (18) years of age to access or use the Services. By using the platform, you represent and warrant that you meet this age requirement and have the legal capacity to enter into these Terms.`,
        `We reserve the right to suspend or terminate access if we reasonably believe that a user is under the required age or has provided false information regarding eligibility.`,
      ],
    },

    {
      heading: "Account Responsibility",
      paragraphs: [
        `You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to notify us immediately of any unauthorized use or suspected breach of security.`,
        `We are not responsible for losses arising from unauthorized access resulting from your failure to safeguard your credentials.`,
      ],
    },

    {
      heading: "Payments and Digital Credits",
      paragraphs: [
        `Certain features of the Services require payment through digital credits or subscriptions. Payments are processed by third-party payment providers. ${COMPANY_NAME} does not store full payment card numbers, CVV codes, or banking credentials.`,
        `Digital credits are not legal tender, do not represent real currency, have no cash value, and are non-transferable unless expressly permitted. Credits may only be used to access Services within the platform.`,
      ],
    },

    {
      heading: "Subscriptions",
      paragraphs: [
        `Subscription plans are billed on a recurring basis in accordance with the pricing and billing terms presented at the time of purchase. By subscribing, you authorize recurring charges until cancellation.`,
        `You may cancel your subscription at any time through your account settings. Cancellation prevents future billing but does not automatically refund the current billing period unless otherwise required by applicable law.`,
      ],
    },

    {
      heading: "Acceptable Use",
      paragraphs: [
        `You agree to use the Services only for lawful purposes and in accordance with all applicable laws and regulations. You must not engage in conduct that is harmful, abusive, fraudulent, or otherwise violates platform policies.`,
        `We reserve the right to investigate and take appropriate action against any violation, including suspension or termination of access.`,
      ],
    },

    {
      heading: "Intellectual Property",
      paragraphs: [
        `All content, software, design, trademarks, logos, and intellectual property associated with the Services are owned by or licensed to ${COMPANY_NAME}.`,
        `You are granted a limited, non-exclusive, non-transferable, revocable license to use the Services solely for personal and lawful purposes. No rights are granted beyond those expressly stated in these Terms.`,
      ],
    },

    {
      heading: "Service Availability",
      paragraphs: [
        `We do not guarantee uninterrupted or error-free operation of the Services. Access may be suspended for maintenance, security, technical issues, or operational reasons.`,
        `We reserve the right to modify, update, or discontinue any part of the Services at any time without prior notice.`,
      ],
    },

    {
      heading: "Limitation of Liability",
      paragraphs: [
        `To the maximum extent permitted by law, ${COMPANY_NAME} shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from or related to your use of the Services.`,
        `Our total liability, if any, shall not exceed the amount you have paid to ${COMPANY_NAME} in the twelve (12) months preceding the event giving rise to the claim.`,
      ],
    },

    {
      heading: "Disclaimer of Warranties",
      paragraphs: [
        `The Services are provided on an “as is” and “as available” basis. We make no warranties, express or implied, regarding the accuracy, reliability, or suitability of the Services.`,
        `We disclaim all warranties including merchantability, fitness for a particular purpose, and non-infringement.`,
      ],
    },

    {
      heading: "Termination",
      paragraphs: [
        `We may suspend or terminate your access at any time, with or without notice, if we reasonably believe you have violated these Terms or applicable laws.`,
        `Upon termination, your right to use the Services will immediately cease.`,
      ],
    },

    {
      heading: "Governing Law",
      paragraphs: [
        `These Terms shall be governed by and construed in accordance with the laws applicable in the jurisdiction in which ${COMPANY_NAME} is registered, without regard to conflict of law principles.`,
      ],
    },

    {
      heading: "Changes to Terms",
      paragraphs: [
        `We may update these Terms from time to time. Continued use of the Services after changes are posted constitutes acceptance of the updated Terms.`,
      ],
    },

    {
      heading: "Contact Information",
      paragraphs: [
        `For legal inquiries, contact: ${LEGAL_EMAIL}`,
        `For support inquiries, contact: ${SUPPORT_EMAIL}`,
      ],
    },

  ],
},
privacy: {
  title: "Privacy Policy",
  lastUpdated,
  intro: [
    `This Privacy Policy explains how ${COMPANY_NAME} (“we”, “us”, or “our”) collects, uses, stores, and protects personal information when you access or use our Services. By using the platform, you consent to the practices described in this policy.`,
  ],
  sections: [

    {
      heading: "Data Collection",
      paragraphs: [
        `We collect information that you voluntarily provide when creating an account, communicating with the platform, making payments, or contacting support. This may include your email address, username, transaction references, device identifiers, IP address, and interaction metadata.`,
        `We also collect technical and usage information automatically through system logs and similar technologies for security, performance, and fraud prevention purposes.`,
        `We do not intentionally collect sensitive personal information unless required to comply with legal obligations.`,
      ],
    },

    {
      heading: "Purpose of Data Use",
      paragraphs: [
        `We use collected data solely to operate, maintain, secure, and improve the Services, process transactions, manage subscriptions, prevent fraud, comply with legal obligations, and provide customer support.`,
        `Data is not used for advertising profiling or third-party marketing purposes.`,
      ],
    },

    {
      heading: "Data Sharing",
      paragraphs: [
        `We do not sell, rent, trade, license, or otherwise share personal data with third parties for commercial or marketing purposes.`,
        `Personal data is processed internally by ${COMPANY_NAME} and is accessible only to authorized personnel for operational, security, and legal compliance purposes.`,
        `Data may be disclosed only when required by law, court order, or lawful government request.`,
      ],
    },

    {
      heading: "International Processing",
      paragraphs: [
        `Personal data may be processed on infrastructure located in different jurisdictions. Appropriate safeguards are applied to ensure compliance with applicable privacy and data protection regulations.`,
      ],
    },

    {
      heading: "Data Security",
      paragraphs: [
        `We implement administrative, technical, and organizational safeguards designed to protect personal data from unauthorized access, disclosure, alteration, or destruction.`,
        `Despite these safeguards, no electronic system can be guaranteed to be completely secure.`,
      ],
    },

    {
      heading: "Data Retention",
      paragraphs: [
        `We retain personal data only for as long as necessary to fulfill operational, legal, and compliance requirements. Data that is no longer required is securely deleted or anonymized.`,
      ],
    },

    {
      heading: "User Rights",
      paragraphs: [
        `You may request access to, correction of, or deletion of your personal data by contacting ${LEGAL_EMAIL}. Requests are subject to identity verification and applicable legal limitations.`,
      ],
    },

    {
      heading: "Cookies and Tracking Technologies",
      paragraphs: [
        `We use cookies and similar technologies solely for functionality, security, and performance purposes. You may control cookie preferences through your browser settings.`,
      ],
    },

    {
      heading: "Third-Party Links",
      paragraphs: [
        `The Services may contain links to external websites. We are not responsible for the privacy practices of those external sites.`,
      ],
    },

    {
      heading: "Policy Updates",
      paragraphs: [
        `This Privacy Policy may be updated from time to time. Continued use of the Services constitutes acceptance of the revised policy.`,
      ],
    },

    {
      heading: "Contact",
      paragraphs: [
        `For privacy-related inquiries or requests, contact: ${LEGAL_EMAIL}`,
      ],
    },

  ],
},

refunds: {
  title: "Refund Policy",
  lastUpdated,
  intro: [
    `This Refund Policy explains the conditions under which refunds may be requested and processed when using ${COMPANY_NAME} Services.`,
  ],
  sections: [

    {
      heading: "Refund Eligibility",
      paragraphs: [
        `Refunds may be requested only for unused digital credits or for transactions that were processed in error. All refund requests are subject to internal review and approval by ${COMPANY_NAME}.`,
        `Refunds are not guaranteed and will be granted solely at our discretion unless otherwise required by applicable consumer protection laws.`,
      ],
    },

    {
      heading: "Refund Process",
      paragraphs: [
        `To request a refund, users must submit a support request providing transaction details, account identification, and the reason for the request. Approved refunds will be processed back to the original payment method used for the transaction.`,
        `Refund processing times may vary depending on the payment provider and financial institution.`,
      ],
    },

    {
      heading: "Digital Credits",
      paragraphs: [
        `Digital credits are provided for immediate access to digital services and are generally non-refundable once used in whole or in part.`,
        `Unused credits may be eligible for refund only where required by law or in exceptional circumstances approved by ${COMPANY_NAME}.`,
      ],
    },

    {
      heading: "Subscriptions",
      paragraphs: [
        `Subscription fees are billed in advance for each billing cycle. Once a billing cycle has commenced, subscription fees are non-refundable, except where mandated by applicable law.`,
        `Cancellation of a subscription prevents future billing but does not entitle the user to a refund for the current billing period.`,
      ],
    },

    {
      heading: "Chargebacks and Payment Disputes",
      paragraphs: [
        `Initiating a chargeback or payment dispute without first contacting support may result in suspension or termination of the account.`,
        `We reserve the right to provide transaction records and usage data to payment providers to resolve disputes.`,
      ],
    },

    {
      heading: "Influencer Departure and Credit Transfers",
      paragraphs: [
        `If an influencer is removed from or chooses to leave the ${COMPANY_NAME} platform, access to that influencer's AI persona, conversations, and related content may immediately cease.`,
        `Users will be notified through the platform and prompted to select a new ${COMPANY_NAME} influencer AI persona for the transfer of any remaining unused credits associated with the departed influencer.`,
        `To support the transition, ${COMPANY_NAME} will provide an additional 10% bonus credit based on the transferred balance.`,
        `Following an influencer's departure, users will no longer be able to interact with the former influencer AI persona or access related content and conversations through the platform.`,
        `Credits associated with departed influencers are non-refundable and must be transferred in accordance with this policy.`,
      ],
    },

    {
      heading: "Legal Exceptions",
      paragraphs: [
        `Nothing in this policy limits statutory consumer rights that cannot be waived under applicable law.`,
      ],
    },

    {
      heading: "Contact",
      paragraphs: [
        `For refund inquiries, contact: ${SUPPORT_EMAIL}`,
      ],
    },

  ],
},

subscriptions: {
  title: "Subscription Policy",
  lastUpdated,
  intro: [
    `This Subscription Policy governs all recurring billing arrangements for ${COMPANY_NAME} subscription services. By subscribing, you agree to the terms outlined in this policy.`,
  ],
  sections: [

    {
      heading: "Billing",
      paragraphs: [
        `Subscriptions are billed in advance on a recurring monthly basis at the rate presented at the time of purchase. By completing a subscription transaction, you authorize ${COMPANY_NAME} to automatically charge the selected payment method on each billing cycle until the subscription is cancelled.`,
        `Billing dates are calculated based on the original subscription start date. Failure of a payment method may result in suspension of subscription benefits until payment is successfully processed.`,
      ],
    },

    {
      heading: "Automatic Renewal",
      paragraphs: [
        `Subscriptions automatically renew at the end of each billing period unless cancelled prior to the renewal date. Renewal charges will be processed using the payment method on file.`,
        `You acknowledge that recurring billing is a condition of subscription access.`,
      ],
    },

    {
      heading: "Cancellation",
      paragraphs: [
        `You may cancel your subscription at any time through your account management settings. Cancellation prevents future billing but does not terminate access to subscription benefits until the end of the current billing period.`,
        `No refunds are issued for partial billing periods unless required by applicable consumer protection laws.`,
      ],
    },

    {
      heading: "Pricing Changes",
      paragraphs: [
        `${COMPANY_NAME} reserves the right to modify subscription pricing. Any pricing changes will be communicated in advance and will apply only to future billing cycles.`,
      ],
    },

    {
      heading: "Suspension or Termination",
      paragraphs: [
        `${COMPANY_NAME} may suspend or terminate subscription access if payment fails, if fraudulent activity is suspected, or if account conduct violates platform policies.`,
      ],
    },

    {
      heading: "No Ownership Rights",
      paragraphs: [
        `Subscription access provides a limited, revocable right to use premium features. No ownership or permanent rights are granted.`,
      ],
    },

    {
      heading: "Legal Rights",
      paragraphs: [
        `Nothing in this policy limits any non-waivable consumer rights under applicable law.`,
      ],
    },

    {
      heading: "Contact",
      paragraphs: [
        `For subscription inquiries, contact: ${SUPPORT_EMAIL}`,
      ],
    },

  ],
},

acceptableUse: {
  title: "Acceptable Use Policy",
  lastUpdated,
  intro: [
    `This Acceptable Use Policy defines the standards of conduct required when accessing or using ${COMPANY_NAME} Services. By using the platform, you agree to comply with this policy.`,
  ],
  sections: [

    {
      heading: "Lawful and Responsible Use",
      paragraphs: [
        `You agree to use the Services only for lawful purposes and in accordance with all applicable laws, regulations, and platform policies.`,
        `You must not use the Services in any manner that could damage, disable, overburden, or impair the platform or interfere with other users’ access.`,
      ],
    },

    {
      heading: "Prohibited Use",
      paragraphs: [
        `You must not engage in any activity that is illegal, abusive, harmful, deceptive, fraudulent, or otherwise inconsistent with the intended use of the Services.`,
        `Prohibited conduct includes attempting to bypass system safeguards, exploiting technical vulnerabilities, engaging in harassment or intimidation, distributing unlawful material, or attempting to gain unauthorized access to accounts or systems.`,
      ],
    },

    {
      heading: "Security and Integrity",
      paragraphs: [
        `You must not introduce malware, bots, automated scripts, or any technology designed to interfere with the proper functioning or security of the Services.`,
        `Any attempt to reverse engineer, scrape, or harvest data from the platform without authorization is strictly prohibited.`,
      ],
    },

    {
      heading: "Enforcement",
      paragraphs: [
        `${COMPANY_NAME} reserves the right to investigate suspected violations and take appropriate enforcement action, including warnings, restriction of access, suspension, termination, and reporting to authorities where required.`,
      ],
    },

    {
      heading: "User Responsibility",
      paragraphs: [
        `You are solely responsible for your conduct while using the Services and for any consequences resulting from misuse.`,
      ],
    },

    {
      heading: "Policy Updates",
      paragraphs: [
        `This Acceptable Use Policy may be updated from time to time. Continued use of the Services constitutes acceptance of any revisions.`,
      ],
    },

    {
      heading: "Contact",
      paragraphs: [
        `Questions regarding acceptable use may be directed to ${SUPPORT_EMAIL}.`,
      ],
    },

  ],
},

adultContent: {
  title: "Adult Content Policy",
  lastUpdated,
  intro: [
    `This Adult Content Policy governs access to and use of age-restricted features provided by ${COMPANY_NAME}. By accessing any adult features, you confirm that you are at least eighteen (18) years of age and agree to comply with this policy.`,
  ],
  sections: [

    {
      heading: "Age Restriction",
      paragraphs: [
        `Adult features are strictly limited to users who are at least eighteen (18) years old. By enabling or accessing adult features, you represent and warrant that you meet this age requirement.`,
        `${COMPANY_NAME} reserves the right to suspend or terminate access to adult features if age eligibility is misrepresented or cannot be reasonably verified.`,
      ],
    },

    {
      heading: "Permitted Adult Content",
      paragraphs: [
        `Adult content available on the platform is intended solely for consensual, lawful, fictional, and simulated adult entertainment purposes.`,
        `All adult interactions are generated through automated systems and do not involve live human participation.`,
      ],
    },

    {
      heading: "Prohibited Content",
      paragraphs: [
        `No content that is illegal, exploitative, abusive, harmful, or non-consensual is permitted under any circumstances.`,
        `Content involving minors, coercion, trafficking, violence, bestiality, incest, or any form of sexual exploitation is strictly prohibited.`,
      ],
    },

    {
      heading: "User Responsibility",
      paragraphs: [
        `Users are solely responsible for ensuring that their use of adult features complies with all applicable laws in their jurisdiction.`,
        `${COMPANY_NAME} does not guarantee that adult content is lawful in every jurisdiction and assumes no responsibility for user compliance with local regulations.`,
      ],
    },

    {
      heading: "Moderation and Enforcement",
      paragraphs: [
        `${COMPANY_NAME} reserves the right to monitor, restrict, remove, or block adult content and user access where violations of this policy or applicable laws are identified.`,
        `Violations may result in immediate suspension or termination of access to adult features and/or the platform.`,
      ],
    },

    {
      heading: "No Professional or Real Relationship Representation",
      paragraphs: [
        `All adult interactions are fictional, simulated, and for entertainment purposes only. No content represents real relationships, real persons, or real emotional commitments.`,
      ],
    },

    {
      heading: "Policy Updates",
      paragraphs: [
        `This Adult Content Policy may be updated at any time. Continued use of adult features constitutes acceptance of any revised terms.`,
      ],
    },

    {
      heading: "Contact",
      paragraphs: [
        `Questions regarding this policy may be directed to ${SUPPORT_EMAIL}.`,
      ],
    },

  ],
},

aiDisclosure: {
  title: "AI Disclosure Policy",
  lastUpdated,
  intro: [
    `This AI Disclosure Policy explains the nature of artificial intelligence systems used within ${COMPANY_NAME} and how users interact with them.`,
  ],
  sections: [

    {
      heading: "AI Nature",
      paragraphs: [
        `All conversations, messages, audio outputs, and interactions available through the Services are generated by artificial intelligence systems. No real human participates in, controls, or directly responds within any conversational session.`,
        `AI-generated content is designed for entertainment and simulated interaction purposes only and does not represent the thoughts, intentions, or communications of any real person.`,
      ],
    },

    {
      heading: "No Human Representation",
      paragraphs: [
        `Users acknowledge that any perceived personality, emotional expression, or conversational behavior is the result of algorithmic generation and does not indicate the presence of a real individual.`,
        `AI personas are fictional representations created for entertainment purposes.`,
      ],
    },

    {
      heading: "Accuracy and Reliability",
      paragraphs: [
        `AI-generated content may be inaccurate, incomplete, or inappropriate. ${COMPANY_NAME} does not guarantee the accuracy, reliability, or suitability of any AI-generated output.`,
        `Users must not rely on AI-generated content as professional, legal, medical, financial, or personal advice.`,
      ],
    },

    {
      heading: "User Responsibility",
      paragraphs: [
        `You acknowledge that you are solely responsible for how you interpret and use AI-generated content.`,
        `${COMPANY_NAME} is not responsible for decisions or actions taken based on AI-generated responses.`,
      ],
    },

    {
      heading: "System Limitations",
      paragraphs: [
        `AI systems operate based on programmed models and data patterns and may produce unexpected, inconsistent, or incorrect responses.`,
        `We do not guarantee uninterrupted or error-free AI operation.`,
      ],
    },

    {
      heading: "Ethical and Legal Compliance",
      paragraphs: [
        `${COMPANY_NAME} designs AI systems to comply with applicable laws, safety standards, and content restrictions.`,
        `Any attempt to misuse AI systems in violation of platform policies is strictly prohibited.`,
      ],
    },

    {
      heading: "Policy Updates",
      paragraphs: [
        `This AI Disclosure Policy may be updated from time to time. Continued use of the Services constitutes acceptance of the revised policy.`,
      ],
    },

    {
      heading: "Contact",
      paragraphs: [
        `Questions regarding AI usage or disclosures may be directed to ${SUPPORT_EMAIL}.`,
      ],
    },

  ],
},

contentModeration: {
  title: "Content Moderation Policy",
  lastUpdated,
  intro: [
    `This Content Moderation Policy explains how ${COMPANY_NAME} monitors, reviews, and enforces content standards across the platform in order to maintain safety, legality, and compliance.`,
  ],
  sections: [

    {
      heading: "Moderation Framework",
      paragraphs: [
        `${COMPANY_NAME} applies a combination of automated systems and human oversight to detect, review, and manage content that may violate platform policies or applicable laws.`,
        `Moderation measures are designed to promote user safety, prevent harmful conduct, and maintain regulatory compliance.`,
      ],
    },

    {
      heading: "Automated Review",
      paragraphs: [
        `Automated systems may analyze content and user behavior to identify potential violations, risks, or prohibited activity.`,
        `Automated detection does not guarantee accuracy and may result in content being flagged for further review.`,
      ],
    },

    {
      heading: "Human Oversight",
      paragraphs: [
        `Where appropriate, flagged content may be reviewed by authorized personnel for policy compliance.`,
        `Moderation decisions may include content removal, access restriction, account warnings, suspension, or termination.`,
      ],
    },

    {
      heading: "User Reporting",
      paragraphs: [
        `Users may report content or behavior that they believe violates platform policies. Reports are reviewed in accordance with moderation procedures.`,
      ],
    },

    {
      heading: "No Guarantee of Detection",
      paragraphs: [
        `${COMPANY_NAME} does not guarantee that all inappropriate or prohibited content will be identified or removed. Users acknowledge that moderation systems have limitations.`,
      ],
    },

    {
      heading: "Enforcement Actions",
      paragraphs: [
        `${COMPANY_NAME} reserves the right to take enforcement action at its discretion based on policy violations, legal requirements, or risk assessments.`,
        `Enforcement actions may be taken with or without prior notice.`,
      ],
    },

    {
      heading: "Appeals",
      paragraphs: [
        `Users may contact support to request review of moderation actions. ${COMPANY_NAME} retains final discretion in all moderation determinations.`,
      ],
    },

    {
      heading: "Legal Compliance",
      paragraphs: [
        `Content moderation practices are designed to comply with applicable laws, regulatory obligations, and platform risk standards.`,
      ],
    },

    {
      heading: "Policy Updates",
      paragraphs: [
        `This Content Moderation Policy may be updated from time to time. Continued use of the Services constitutes acceptance of the revised policy.`,
      ],
    },

    {
      heading: "Contact",
      paragraphs: [
        `Questions regarding content moderation may be directed to ${SUPPORT_EMAIL}.`,
      ],
    },

  ],
},

dataRetention: {
  title: "Data Retention & Deletion Policy",
  lastUpdated,
  intro: [
    `This Data Retention & Deletion Policy explains how ${COMPANY_NAME} retains, protects, and deletes personal and transactional data in accordance with legal, operational, and security requirements.`,
  ],
  sections: [

    {
      heading: "Retention Purpose",
      paragraphs: [
        `We retain personal and transactional data only for as long as necessary to provide the Services, comply with legal and regulatory obligations, resolve disputes, enforce agreements, and maintain system security.`,
        `Transaction records may be retained for accounting, fraud prevention, and compliance purposes in accordance with applicable laws.`,
      ],
    },

    {
      heading: "Personal Data Protection",
      paragraphs: [
        `Personal data such as first name, last name, email address, and account identifiers are stored in encrypted form using industry-standard cryptographic protection.`,
        `Payment information is processed through secure third-party payment systems. ${COMPANY_NAME} does not store full credit card numbers, CVV codes, or sensitive payment credentials. Any payment references retained are encrypted and tokenized where applicable.`,
      ],
    },

    {
      heading: "Conversation Data",
      paragraphs: [
        `User conversations, including text and audio interaction data, are encrypted both in transit and at rest.`,
        `Conversation data is retained only as necessary for service functionality, moderation, dispute resolution, and legal compliance.`,
      ],
    },

    {
      heading: "Access Control",
      paragraphs: [
        `Access to retained data is restricted to authorized personnel only and is governed by strict internal security and audit controls.`,
      ],
    },

    {
      heading: "Deletion and Anonymization",
      paragraphs: [
        `When personal data is no longer required for legal, operational, or security purposes, it is securely deleted or anonymized using industry-standard deletion procedures.`,
        `Users may request deletion of their personal data subject to applicable legal retention obligations.`,
      ],
    },

    {
      heading: "Legal Retention Obligations",
      paragraphs: [
        `Certain data may be retained for longer periods where required by law, regulatory authorities, court orders, or financial compliance requirements.`,
      ],
    },

    {
      heading: "Security Commitment",
      paragraphs: [
        `${COMPANY_NAME} implements technical, organizational, and administrative safeguards to protect retained data against unauthorized access, loss, alteration, or disclosure.`,
        `Despite these safeguards, no system can guarantee absolute security.`,
      ],
    },

    {
      heading: "Policy Updates",
      paragraphs: [
        `This Data Retention & Deletion Policy may be updated from time to time. Continued use of the Services constitutes acceptance of the revised policy.`,
      ],
    },

    {
      heading: "Contact",
      paragraphs: [
        `For data retention or deletion inquiries, contact: ${LEGAL_EMAIL}`,
      ],
    },

  ],
},

ageVerification: {
  title: "Age Verification Statement",
  lastUpdated,
  intro: [
    `This Age Verification Statement explains how ${COMPANY_NAME} enforces age restrictions to ensure that only eligible users access the Services.`,
  ],
  sections: [

    {
      heading: "Minimum Age Requirement",
      paragraphs: [
        `Access to the Services is strictly limited to individuals who are at least eighteen (18) years of age. By creating an account or using the platform, you represent and warrant that you meet this age requirement.`,
      ],
    },

    {
      heading: "Current Verification Method",
      paragraphs: [
        `At present, age verification is performed through a mandatory user declaration and confirmation checkbox during account registration or before accessing age-restricted features.`,
        `Providing false or misleading age information constitutes a violation of platform policies and may result in immediate suspension or termination of access.`,
      ],
    },

    {
      heading: "Future Verification Methods",
      paragraphs: [
        `${COMPANY_NAME} reserves the right to implement additional age verification measures in the future, including the use of trusted third-party identity or facial age-estimation technologies, where legally permitted.`,
        `Any such verification processes will be conducted in accordance with applicable privacy, data protection, and biometric information laws.`,
      ],
    },

    {
      heading: "User Responsibility",
      paragraphs: [
        `Users are solely responsible for ensuring the accuracy of their age declaration and for complying with age-based access requirements under applicable laws.`,
      ],
    },

    {
      heading: "Enforcement",
      paragraphs: [
        `${COMPANY_NAME} may restrict, suspend, or terminate access where age eligibility cannot be reasonably verified or is found to be misrepresented.`,
      ],
    },

    {
      heading: "Legal Compliance",
      paragraphs: [
        `Age verification practices are designed to comply with applicable child protection, consumer protection, and online safety regulations.`,
      ],
    },

    {
      heading: "Policy Updates",
      paragraphs: [
        `This Age Verification Statement may be updated as verification technologies or legal requirements evolve. Continued use of the Services constitutes acceptance of any revised terms.`,
      ],
    },

    {
      heading: "Contact",
      paragraphs: [
        `Questions regarding age verification may be directed to ${SUPPORT_EMAIL}.`,
      ],
    },

  ],
},

cookies: {
  title: "Cookie Policy",
  lastUpdated,
  intro: [
    `This Cookie Policy explains how ${COMPANY_NAME} uses cookies and similar technologies to operate and improve the Services.`,
  ],
  sections: [

    {
      heading: "Cookie Usage",
      paragraphs: [
        `Cookies are small text files stored on your device when you access the Services. They help enable core platform functionality, security features, performance optimization, and user experience improvements.`,
        `We use cookies for essential operational purposes only, including authentication, session management, fraud prevention, and system stability.`,
      ],
    },

    {
      heading: "Types of Cookies",
      paragraphs: [
        `Cookies used by ${COMPANY_NAME} may include session cookies, persistent cookies, and security cookies. These cookies do not contain sensitive personal information and are not used for third-party advertising or behavioral profiling.`,
      ],
    },

    {
      heading: "User Control",
      paragraphs: [
        `You may control or disable cookies through your browser or device settings. Please note that disabling cookies may affect the functionality and availability of certain features of the Services.`,
      ],
    },

    {
      heading: "No Third-Party Advertising Cookies",
      paragraphs: [
        `${COMPANY_NAME} does not use third-party advertising, tracking, or marketing cookies.`,
      ],
    },

    {
      heading: "Security and Privacy",
      paragraphs: [
        `Cookies used by the platform are designed to operate in compliance with applicable privacy and data protection regulations and do not store payment credentials, passwords, or sensitive personal information.`,
      ],
    },

    {
      heading: "Policy Updates",
      paragraphs: [
        `This Cookie Policy may be updated from time to time to reflect operational or regulatory changes. Continued use of the Services constitutes acceptance of the revised policy.`,
      ],
    },

    {
      heading: "Contact",
      paragraphs: [
        `For questions regarding this Cookie Policy, contact: ${LEGAL_EMAIL}`,
      ],
    },

  ],
},

contentAgreement: {
  title: "Content Agreement",
  lastUpdated: contentAgreementLastUpdated,
  intro: [
    `This Agreement is entered into by and between ${COMPANY_NAME} (the "Company") and the individual signing this agreement (the "Creator"). By providing assets to the Company and accessing the ${COMPANY_NAME} platform, the Creator agrees to the following terms:`,
  ],
  sections: [

    {
      heading: "Age Representation & Verification",
      paragraphs: [
        `The Creator hereby warrants and represents that they are at least 18 years of age (or the legal age of majority in their jurisdiction). The Creator understands that providing false information regarding their age is a violation of law and will result in immediate termination of this agreement and potential legal action.`,
      ],
    },

    {
      heading: "Grant of License",
      paragraphs: [
        `The Creator grants ${COMPANY_NAME} a non-exclusive, worldwide, royalty-free license to use the image and video library provided by the Creator (the "Assets") for the purpose of creating, promoting, and operating an AI version of the Creator's likeness (the "Persona").`,
      ],
    },

    {
      heading: "Authorization for Synthetic Content",
      paragraphs: [
        `The Creator expressly grants ${COMPANY_NAME} permission to use the Assets as training data or reference material for generative artificial intelligence. This includes, but is not limited to:`,
      ],
      bullets: [
        `Landing Pages: The creation of marketing visuals and promotional banners.`,
        `Synthetic Scenarios: The creation of "synthetic scenarios," wherein AI is used to generate images or videos of the Creator in digital environments, settings, or situations that were not present in the original Assets provided.`,
        `AI Marketing Materials: The generation of synthetic imagery for use on social media and other marketing channels to promote the ${COMPANY_NAME} Persona.`,
      ],
    },

    {
      heading: "Limitation of Use (Marketing Only)",
      paragraphs: [
        `The license granted herein is strictly for marketing and persona-development purposes. ${COMPANY_NAME} agrees that it shall not sell the Creator's raw Assets as standalone products to third parties. The use of synthetic imagery is intended solely to attract users to the Persona and enhance the user experience within the ${COMPANY_NAME} ecosystem.`,
      ],
    },

    {
      heading: "Ownership",
      paragraphs: [
        `Original Assets: The Creator retains all ownership rights to the original images and videos provided to the Company.`,
        `Derived Works: Any AI-generated imagery, synthetic scenarios, or marketing materials created by ${COMPANY_NAME} shall be owned by the Company for the duration of this agreement.`,
      ],
    },

    {
      heading: "Withdrawal of Consent & Right to Be Forgotten",
      paragraphs: [
        `The Creator maintains the right to withdraw their consent and request the deletion of their Persona.`,
        `Request Process: To initiate a deletion, the Creator must submit a written request to the Company.`,
        `Deletion Timeline: Upon receipt of a valid request, ${COMPANY_NAME} agrees to delete the AI Persona and remove associated marketing assets from active use within fourteen (14) calendar days.`,
        `Final Payment: Upon termination of this agreement via withdrawal of consent, ${COMPANY_NAME} will calculate and issue any outstanding payments owed to the Creator up to the date of the deletion request.`,
      ],
    },

    {
      heading: "Influencer Account Deletion and User Credit Transfers",
      paragraphs: [
        `An influencer may request deletion or removal of their account from the ${COMPANY_NAME} platform at any time by submitting a formal account deletion request through the platform or designated support channels.`,
        `Following submission of a deletion request, the influencer acknowledges and agrees that account deletion may not occur immediately. ${COMPANY_NAME} may retain the influencer account for up to fourteen (14) days, or until the completion of the current payment cycle, in order to process outstanding earnings, commissions, chargeback reviews, adjustments, or other financial obligations associated with the account.`,
        `Once the applicable payment cycle has been completed and all approved commissions or earnings owed to the influencer have been paid, ${COMPANY_NAME} may permanently disable or remove the influencer's AI persona, profile, content, conversations, media, and related services from user access.`,
        `Following removal of the influencer from the platform:`,
      ],
      bullets: [
        `Users will no longer be able to interact with the influencer's AI persona or access associated content or conversations.`,
        `Users with remaining unused credits connected to the departing influencer may be notified and provided with a platform-managed credit transfer process to another available influencer AI persona.`,
        `Any replacement or transferred user credits are issued solely by ${COMPANY_NAME} as a platform-funded promotional or service continuity measure and are not funded, reimbursed, or payable by the departing influencer.`,
      ],
    },

    {
      heading: "Departing Influencer Acknowledgements",
      paragraphs: [
        `The departing influencer acknowledges and agrees that:`,
      ],
      bullets: [
        `They have no ownership rights, royalty rights, commission rights, revenue share rights, or continuing financial interest in any future user spending, credits, subscriptions, or purchases made with another influencer following a transfer.`,
        `Users transferred to another influencer AI persona shall be treated as users of the newly selected influencer for all future platform activity and revenue allocation purposes.`,
        `${COMPANY_NAME} retains sole discretion regarding user migration, transfer mechanics, platform continuity measures, bonus credits, and the handling of inactive or departing influencer accounts.`,
      ],
    },

    {
      heading: "Indemnification & Warranties",
      paragraphs: [
        `The Creator warrants that they have the full legal right to grant this license and that the Assets provided do not infringe upon the intellectual property or privacy rights of any third party. The Creator agrees to indemnify ${COMPANY_NAME} against any claims arising from a breach of these warranties.`,
        `${COMPANY_NAME} reserves the right to suspend, delay, or deny account deletion requests where required for fraud prevention, legal compliance, payment disputes, investigations, or enforcement of platform policies.`,
      ],
    },

  ],
},

 prohibitedContent: {
  title: "Prohibited Content Appendix",
  lastUpdated,
  intro: [
    `This appendix lists content, conduct, and activity that are strictly prohibited on ${COMPANY_NAME}.`,
    `These restrictions apply to all users, all features, and all interaction modes, including any age-restricted, subscription-based, or premium services.`,
  ],
  sections: [

    {
      heading: "Zero-Tolerance Prohibitions",
      paragraphs: [
        `The following categories of content and conduct are strictly prohibited under all circumstances. Any violation may result in immediate enforcement action, including content removal, account suspension, account termination, reporting to relevant authorities, and permanent access restriction.`,
        `These prohibitions exist to protect users, comply with applicable laws, and maintain platform integrity.`,
      ],
      bullets: [
        `Any content involving minors, including sexualized depiction, roleplay, age simulation, or suggestion of underage involvement.`,
        `Non-consensual, coercive, exploitative, or abusive content or behavior.`,
        `Human trafficking, sexual exploitation, prostitution facilitation, or any illegal activity.`,
        `Bestiality, incest, or any content involving animals or prohibited familial relationships.`,
        `Extreme violence, sexual violence, torture, or glorification of physical harm.`,
      ],
    },

    {
      heading: "Illegal or Harmful Conduct",
      paragraphs: [
        `Content or conduct that violates local, national, or international laws is strictly prohibited.`,
        `Users must not use the Services to promote, encourage, or participate in criminal, abusive, or harmful activities.`,
      ],
    },

    {
      heading: "Financial Abuse and Fraud",
      paragraphs: [
        `Any attempt to defraud ${COMPANY_NAME}, payment processors, or other users is prohibited.`,
        `This includes chargeback abuse, use of stolen payment methods, identity fraud, money laundering, or payment manipulation.`,
      ],
    },

    {
      heading: "Platform Security Violations",
      paragraphs: [
        `Users must not attempt to reverse engineer, scrape, exploit, manipulate, or interfere with platform systems, infrastructure, or security controls.`,
        `Malware distribution, phishing, account compromise, automation abuse, or unauthorized access attempts are strictly prohibited.`,
      ],
    },

    {
      heading: "Circumvention of Safeguards",
      paragraphs: [
        `Any attempt to bypass moderation systems, age restrictions, payment controls, or safety mechanisms is prohibited.`,
      ],
    },

    {
      heading: "Enforcement and Consequences",
      paragraphs: [
        `${COMPANY_NAME} reserves the right to take immediate and appropriate enforcement action against any violation of this policy.`,
        `Enforcement actions may include warnings, content removal, access restriction, suspension, termination, permanent banning, and legal reporting where required.`,
        `Enforcement decisions are final and made at the sole discretion of ${COMPANY_NAME}.`,
      ],
    },

    {
      heading: "Reporting",
      paragraphs: [
        `Users are encouraged to report prohibited content or conduct immediately.`,
        `Reports may be submitted by contacting: ${SUPPORT_EMAIL}.`,
      ],
    },

    {
      heading: "Policy Scope",
      paragraphs: [
        `This appendix forms part of the Terms and Conditions and applies across all areas of the platform without exception.`,
      ],
    },

  ],
},
};
