import { lazy } from "react";

export default {
    Ai: lazy(() => import("@/assets/mj-dashboard/svg/Ai.svg?react")),
    ArrowRight: lazy(() => import("@/assets/mj-dashboard/svg/ArrowRight.svg?react")),
    ArrowLeft: lazy(() => import("@/assets/svg/ArrowLeft.svg?react")),
    ArrowDown: lazy(() => import("@/assets/svg/ArrowDown.svg?react")),
    LightArrowRight: lazy(() => import("@/assets/svg/LightArrowRight.svg?react")),
    Bill: lazy(() => import("@/assets/mj-dashboard/svg/Bill.svg?react")),
    Danger: lazy(() => import("@/assets/mj-dashboard/svg/DangerTriangle.svg?react")),
    Dashboard: lazy(() => import("@/assets/mj-dashboard/svg/dashboard.svg?react")),
    Logout: lazy(() => import("@/assets/mj-dashboard/svg/Logout.svg?react")),
    Profile: lazy(() => import("@/assets/mj-dashboard/svg/Profile.svg?react")),
    Users: lazy(() => import("@/assets/mj-dashboard/svg/Users.svg?react")),
    MoreCircle: lazy(() => import("@/assets/svg/MoreCircle.svg?react")),
    CloseSquare: lazy(() => import("@/assets/mj-dashboard/svg/CloseSquare.svg?react")),
    CloseSquareSolid: lazy(() => import("@/assets/CloseSquare.svg?react")),
    DangerTriangleSmall: lazy(() => import("@/assets/mj-dashboard/svg/Danger.svg?react")),
    DangerCircleSmall: lazy(() => import("@/assets/mj-dashboard/svg/DangerCircle.svg?react")),
    Star: lazy(() => import("@/assets/mj-dashboard/svg/Star.svg?react")),
    StarHollow: lazy(() => import("@/assets/mj-dashboard/svg/StarHollow.svg?react")),
    TickSquare: lazy(() => import("@/assets/mj-dashboard/svg/TickSquare.svg?react")),
    Crown: lazy(() => import("@/assets/mj-dashboard/svg/Crown.svg?react")),
    Triseption: lazy(() => import("@/assets/mj-dashboard/svg/Triseption.svg?react")),
    ChevronUpDown: lazy(() => import("@/assets/mj-dashboard/svg/chevron-up-down.svg?react")),
    Speaker: lazy(() => import("@/assets/svg/Speaker.svg?react")),
    Message: lazy(() => import("@/assets/svg/Message.svg?react")),
    Lock: lazy(() => import("@/assets/svg/Lock.svg?react")),
    Voice: lazy(() => import("@/assets/svg/Voice.svg?react")),
    Muted: lazy(() => import("@/assets/svg/Muted.svg?react")),
    Call: lazy(() => import("@/assets/svg/Call.svg?react")),
    Heart: lazy(() => import("@/assets/svg/Heart.svg?react")),
    ChatRound: lazy(() => import("@/assets/svg/Chat.svg?react")),
    PlusBox: lazy(() => import("@/assets/svg/PlusBox.svg?react")),
    Menu: lazy(() => import("@/assets/svg/Menu.svg?react")),
    Cross: lazy(() => import("@/assets/svg/Cross.svg?react")),
    Delete: lazy(() => import("@/assets/svg/Delete.svg?react")),
    HangupCallIcon: lazy(() => import("@/assets/svg/HangupCall.svg?react")),
    PlusPurple: lazy(() => import("@/assets/svg/PlusPurple.svg?react")),
    InfoCircle: lazy(() => import("@/assets/svg/InfoCircle.svg?react")),
    InfoCircleGray: lazy(() => import("@/assets/svg/InfoCircleGray.svg?react")),
    // CircleTick: lazy(() => import("@/assets/svg/circle_tick.svg?react")),
    // CircleCross: lazy(() => import("@/assets/svg/circle_cross.svg?react")),
    PaymentTick: lazy(() => import("@/assets/svg/PaymentTick.svg?react")),
    PaymentCross: lazy(() => import("@/assets/svg/PaymentCross.svg?react")),

    Chat: lazy(() => import("@/assets/svg/Chat.svg?react")),

    //Influencer Relation Metric
    Trust: lazy(() => import("@/assets/svg/Trust.svg?react")),
    Shield: lazy(() => import("@/assets/svg/Shield.svg?react")),
    KissGray: lazy(() => import("@/assets/svg/KissGray.svg?react")),
    Angles: lazy(() => import("@/assets/svg/Angles.svg?react")),


    //Influencer Relationship Status
    RelHate: lazy(() => import("@/assets/svg/iconHate.svg?react")),
    RelDislike: lazy(() => import("@/assets/svg/iconDislike.svg?react")),
    RelTalking: lazy(() => import("@/assets/svg/iconTalking.svg?react")),
    RelStrangers: lazy(() => import("@/assets/svg/iconStrangers.svg?react")),
    RelFlirting: lazy(() => import("@/assets/svg/iconFlirting.svg?react")),
    RelDating: lazy(() => import("@/assets/svg/iconDating.svg?react")),
    RelInLove: lazy(() => import("@/assets/svg/iconInLove.svg?react")),


    // Social Media Icons
    OnlyFans: lazy(() => import("@/assets/svg/OnlyFans.svg?react")),
    Instagram: lazy(() => import("@/assets/svg/Instagram.svg?react")),
    TikTok: lazy(() => import("@/assets/svg/TikTok.svg?react")),
    SocialInstagramWhite: lazy(() => import("@/assets/svg/iconSocialInstagramWhite.svg?react")),
    SocialInstagramRed: lazy(() => import("@/assets/svg/iconSocialInstagramRed.svg?react")),
    SocialOnlyFansWhite: lazy(() => import("@/assets/svg/iconSocialOnlyFansWhite.svg?react")),
    SocialOnlyFansRed: lazy(() => import("@/assets/svg/iconSocialOnlyFansRed.svg?react")),
    SocialSnapChatWhite: lazy(() => import("@/assets/svg/iconSocialSnapChatWhite.svg?react")),
    SocialSnapChatRed: lazy(() => import("@/assets/svg/iconSocialSnapChatRed.svg?react")),
    SocialTelegramWhite: lazy(() => import("@/assets/svg/iconSocialTelegramWhite.svg?react")),
    SocialTelegramRed: lazy(() => import("@/assets/svg/iconSocialTelegramRed.svg?react")),
    SocialTikTokWhite: lazy(() => import("@/assets/svg/iconSocialTiktTokWhite.svg?react")),
    SocialTikTokRed: lazy(() => import("@/assets/svg/iconSocialTiktTokRed.svg?react")),
    SocialWhatsAppWhite: lazy(() => import("@/assets/svg/iconSocialWhatsAppWhite.svg?react")),
    SocialWhatsAppRed: lazy(() => import("@/assets/svg/iconSocialWhatsAppRed.svg?react")),
    SocialXWhite: lazy(() => import("@/assets/svg/iconSocialXWhite.svg?react")),
    SocialXRed: lazy(() => import("@/assets/svg/iconSocialXRed.svg?react")),
    // End of Social Media Icons

    Calling: lazy(() => import("@/assets/svg/Calling.svg?react")),
    RecordingStart: lazy(() => import("@/assets/svg/iconStartRecording.svg?react")),
    RecordingStop: lazy(() => import("@/assets/svg/iconStopRecording.svg?react")),
    Mail: {
        Outlook: lazy(() => import("@/assets/svg/MicrosoftOutlook2019.svg?react")),
        Yahoo: lazy(() => import("@/assets/svg/YahooMailApp.svg?react")),
        Gmail: lazy(() => import("@/assets/svg/Gmail.svg?react")),
        Mail: lazy(() => import("@/assets/svg/Mail.svg?react")),
    },
    Male: lazy(() => import("@/assets/svg/Male.svg?react")),
    Female: lazy(() => import("@/assets/svg/Female.svg?react")),
    Link: lazy(() => import("@/assets/svg/Link.svg?react")),
    UploadPhoto: lazy(() => import("@/assets/svg/iconUploadPhoto.svg?react")),
    Upload: lazy(() => import("@/assets/svg/iconUpload.svg?react")),
}