export const Paths = {
    all: "*",
    root: "/",
    influencerProfile: (username = ":username") => `/${username}`,
    join: "/join",
    incomeCalculator: "/income-calculator",
    joinRegister: "/join/register",
    thankYou: "/thank-you",
    joinOnboarding: "/join/onboarding",
    voiceTerms: "/voice-terms",
    influencerHome: "/influencer-home",
    influencerHomeExpired: "/influencer-home-expired",
    intencionInfluencerHome: "/intencion-influencer-home",
    login: "/login",
    register: (username = ":username") => `/${username}/register`,
    registerPlain: "/register",
    registerVerify: "/register/verify",
    resetPassword: "/reset-password",
    forgotPassword: "/forgot-password",
    verifyEmail: "/verify-email",
    admin: {
        root: "/admin",
        characters: "/admin/characters",
        influencerCharacter: "/admin/influencer-character",
        gallery: "/admin/gallery",
        influencerAssets: "/admin/influencer-assets",
        emailAssets: "/admin/email-assets",
        influencer: "/admin/influencer",
        prompts: "/admin/prompts",
        relationship: "/admin/relationship",
        preInfluencers: "/admin/pre-influencers",
        preInfluencerDetail: (id = ":pre_influencer_id") =>
            `/admin/pre-influencers/${id}`,
        knowledge: "/admin/knowledge",
        chatHistory: "/admin/chat-history",
        analytics: "/admin/analytics",
        logs: "/admin/logs",
        telegram: "/admin/telegram",
    },
    legal: {
        terms: "/terms",
        privacy: "/privacy",
        refunds: "/refunds",
        subscriptions: "/subscriptions",
        acceptableUse: "/acceptable-use",
        adultContent: "/adult-content",
        aiDisclosure: "/ai-disclosure",
        contentModeration: "/content-moderation",
        dataRetention: "/data-retention",
        ageVerification: "/age-verification",
        cookies: "/cookies",
        prohibitedContent: "/prohibited-content",
    },
    mjDashboard: "/mj/dashboard",

    voice: "/voice",
    home: "/home",
    profile: "/profile",
    paypalReturn: "/paypal/return",
    paypalCancel: "/paypal/cancel",
    diditReturn: "/didit/return",
    armloopReturn: "/armloop/return",
    profileSelector: "/profile-selector",
    adultMode: "/adult-mode",
    underage: "/underage",
    signup: "/signup",

    influencerAudioManager: (influencerId = ":influencer_id") =>
        `/influencer/${influencerId}/audio-manager`,

    testButtons: "/test/buttons",
    testProfilePage: "/test/profile-page",
    chatInfluencerBarPreview: "/test/chat-influencer-bar-preview",
} as const;
